default["ghe-util"]["root_dir"] = '/etc/ghe-util'
default["ghe-util"]["hostname"] = ''
default["ghe-util"]["data_directory"] = 'data'
default["ghe-util"]["number_of_snapshots"] = '10'
default["ghe-util"]["restore_hostname"] = ''
default["ghe-util"]["extra_ssh_options"] = '-i /root/.ssh/github_admin_ssh -oStrictHostKeyChecking=no'
default["ghe-util"]["license_md5"] = ''
default["ghe-util"]["cron"]["mailto"] = 'root'
default["ghe-util"]["cron"]["hour"] = '7'
default["ghe-util"]["cron"]["minute"] = '45'
default["ghe-util"]["cron"]["day"] = '*'
default["ghe-util"]["cron"]["month"] = '*'
default["ghe-util"]["cron"]["weekday"] = '*'